public class Calculator {
    // public static void welcomeMsge() {
    //     system.debug('welcome to apex calc.');

    // }
    // public static void printNewMessage(string msg){
    //     // use parameter variable name inside the method
    //     system.debug(msg);
    // }
    // public static integer add(integer a, integer c){
    //     integer sum = a + c;
    //     return sum;
    // }
    // public static integer add(integer a, integer b, integer c){
    //     return a+b+c;

    // }
    // public static integer add(list<integer> intList){
    //     integer sum = 0;
    //     for (integer eachInt : intList) {
    //         system.debug('eachInt ' + eachInt);
    //         sum+= eachInt;
    //         system.debug('sum  ' + sum);
    //     }

    //     return sum;
    // }
    // public static integer add(list<Integer> listInteger) {
    //     Integer sum1 = 0;
    //     for (integer i : listInteger) {
    //         sum1+=i;
            
    //     }
    //     return sum1;
    // }
    
    // }
