AirLineTickets ticketToBerlin = new AirLineTickets();
ticketToBerlin.arrivalCity = 'Almaty';
ticketToBerlin.departureCity = 'Bonn';
ticketToBerlin.flightNumber = '2e21141';
ticketToBerlin.seatAssigned = '03B';
system.debug(ticketToBerlin);
ticketToBerlin.printTicket();

AirLineTickets ticketToAtyrau = new AirLineTickets();
ticketToAtyrau.arrivalCity = 'Almaty';
ticketToAtyrau.departureCity = 'Atyrau';
ticketToAtyrau.flightNumber = '2e21121';
ticketToAtyrau.seatAssigned = '01B';
system.debug(ticketToAtyrau);
ticketToAtyrau.printTicket();
