public class AddressHW {
   public void homeAddr(){
       string  myName =   'Indira Setzhan';
       integer numberOfFam =  5;
       string  houseName =  'Golden';
       string  houseNumber =   '2088';
       string  streetName =  'Oak park';
       string  cityName =  'Harrison';
       string  stateName =  'TX';
       string  stateIsoCode = '0505';
       string  countryName = 'Harris';
       string  countryIsoCode = '2020';
       string  zipCode = '77450';
       Boolean isCurrenthome = true;      
    
   
       system.debug('myName =   ' + myName );
       system.debug('numberOfFam ' + numberOfFam);
       system.debug('houseName = ' + houseName);
       system.debug('houseNumber ' + houseNumber);
       system.debug('streetName =' + streetName);
       system.debug('cityName =  ' + cityName);
       system.debug('stateName = ' + stateName);
       system.debug('stateIsoCode' + stateIsoCode);
       system.debug('countryName ' + countryName);
       system.debug('countryIsoCode' + countryIsoCode);
       system.debug('zipCode '  + zipCode);
       system.debug('isCurrenthome' + isCurrenthome);
   }
}
