/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 04-25-2022
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public class BasicCalc {
    public integer add(integer x, integer y) {
        integer sum = x + y;
        return sum;

    }
    public decimal average(integer i, integer j){
        integer summa = add(i,j);
        decimal avg = add(i,j)/2;
        return avg;

    }
}
