/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 04-25-2022
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public class Dogs1 {
    public string name;
    public string breed;
    public Integer age;

    public void Description(){
        system.debug('Age of ' + name + ' is ' +age+ ', its breed is ' + breed);
    }
}

