/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 04-25-2022
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public  class Dogs {
    public string Name;
    public string Breed;
    public Integer Age;

    public void Description(){
        system.debug('Age of ' + name + ' is ' +Age+ ', its breed is ' + Breed);

    }

    }

