/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 04-26-2022
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public class Greetings {
    public String language = '';
    public string GreetClass(){
        string Greet = '';
        if(language == 'hindi'){
            greet = 'Namaste';
        }else if(language == 'turkish'){
            greet = 'Merxaba';
        }else if(language == 'Kazakh'){
            greet = 'SalemSalem';
        }else{
            greet = 'HELLOOO';
        }
        return Greet;
    }
}
   




           
        


      
      
      
      
        
          
      
       
          
      
          
      


     
  
 
    
