public  class HomeWork1day {
    public void HomeAddress() {
        String name = 'Ika';
        Integer totalofMembers = 5;
        String houseName = 'Golden House';
        String houseNumber = '8888';
        String streetName = 'Parkway';
        String city = 'Katy';
        String stateISOcode = 'US-TX';
        String country = 'USA';
        String countryISOcode = 'US';
        String zipCode = '77400';
        Boolean isYourCurrentAddress = True;
        System.debug('My name is ' + name);
        System.debug('My house is ' + houseName);
        System.debug('My Address is ' + houseNumber + ' ' + streetName );
        System.debug(city + ' ' + stateISOcode + ' ' + country);
        System.debug(zipCode );
        System.debug('My current address: ' + isYourCurrentAddress);
    }
}